version: "4.13"

services:
  backend:
    build: .
    container_name: todoapp_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-=63d50%s1*n0^5g9$1duq=6icucv0bb)9$%j=j98jdu$1lr%@8j0
      - DEBUG=True